/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.programming3;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author omarm
 */
public class AddTicketFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddTicketFrame
     */
    public AddTicketFrame() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(1000, 500);
        this.setTitle("ITV");
        this.setLocationRelativeTo(null);
        addTicketButton.setBackground(Color.white);
        addTicketButton.setForeground(new Color(35,179,155));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        addTicketButton = new javax.swing.JButton();
        removeTicketButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pictureLabel = new javax.swing.JLabel();
        movieNameLabel = new javax.swing.JLabel();
        hallNameLabel = new javax.swing.JLabel();
        hallNameField = new javax.swing.JTextField();
        movieNameField = new javax.swing.JTextField();
        showTimeLabel = new javax.swing.JLabel();
        showTimeField = new javax.swing.JTextField();
        numberOfTicketsLabel = new javax.swing.JLabel();
        numberOfTicketsField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        vipButton = new javax.swing.JButton();
        failedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(35, 179, 155));

        homeButton.setBackground(new java.awt.Color(35, 179, 155));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("Home");
        homeButton.setBorder(null);
        homeButton.setFocusable(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        addTicketButton.setBackground(new java.awt.Color(35, 179, 155));
        addTicketButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addTicketButton.setForeground(new java.awt.Color(255, 255, 255));
        addTicketButton.setText("Add Ticket");
        addTicketButton.setBorder(null);
        addTicketButton.setFocusable(false);
        addTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTicketButtonActionPerformed(evt);
            }
        });

        removeTicketButton.setBackground(new java.awt.Color(35, 179, 155));
        removeTicketButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        removeTicketButton.setForeground(new java.awt.Color(255, 255, 255));
        removeTicketButton.setText("Remove Ticket");
        removeTicketButton.setBorder(null);
        removeTicketButton.setFocusable(false);
        removeTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTicketButtonActionPerformed(evt);
            }
        });

        profileButton.setBackground(new java.awt.Color(35, 179, 155));
        profileButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        profileButton.setForeground(new java.awt.Color(255, 255, 255));
        profileButton.setText("Profile");
        profileButton.setBorder(null);
        profileButton.setFocusable(false);
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTicketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeTicketButton, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(addTicketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(removeTicketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pictureLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\omarm\\Desktop\\Programming3\\src\\main\\java\\Images\\tickets (2) (1).jpg")); // NOI18N

        movieNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        movieNameLabel.setForeground(new java.awt.Color(35, 179, 155));
        movieNameLabel.setText("Movie Name :");

        hallNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hallNameLabel.setForeground(new java.awt.Color(35, 179, 155));
        hallNameLabel.setText("Hall Name :");

        showTimeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        showTimeLabel.setForeground(new java.awt.Color(35, 179, 155));
        showTimeLabel.setText("Show Time :");

        numberOfTicketsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        numberOfTicketsLabel.setForeground(new java.awt.Color(35, 179, 155));
        numberOfTicketsLabel.setText("Tickets NO :");

        submitButton.setBackground(new java.awt.Color(35, 179, 155));
        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setFocusable(false);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        vipButton.setBackground(new java.awt.Color(0, 0, 0));
        vipButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vipButton.setForeground(new java.awt.Color(212, 175, 55));
        vipButton.setText("VIP");
        vipButton.setFocusable(false);
        vipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vipButtonActionPerformed(evt);
            }
        });

        failedLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        failedLabel.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hallNameLabel)
                            .addComponent(hallNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showTimeLabel)
                            .addComponent(showTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(failedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movieNameLabel)
                            .addComponent(movieNameField)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(submitButton)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numberOfTicketsLabel)
                                    .addComponent(numberOfTicketsField))))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251)))
                .addComponent(pictureLabel))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {hallNameField, hallNameLabel, movieNameField, movieNameLabel, numberOfTicketsField, numberOfTicketsLabel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieNameLabel)
                    .addComponent(hallNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hallNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(showTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numberOfTicketsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberOfTicketsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(failedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(vipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {hallNameField, hallNameLabel, movieNameField, movieNameLabel, numberOfTicketsField, numberOfTicketsLabel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        UserHomeFrame userHomeFrame = new UserHomeFrame();
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void addTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTicketButtonActionPerformed
        AddTicketFrame addTicketFrame = new AddTicketFrame();
        this.dispose();
    }//GEN-LAST:event_addTicketButtonActionPerformed

    private void removeTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTicketButtonActionPerformed
        RemoveTicketFrame removeTicketFrame = new RemoveTicketFrame();
        this.dispose();    }//GEN-LAST:event_removeTicketButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        UserProfileFrame userProfileFrame = new UserProfileFrame();
        this.dispose();
    }//GEN-LAST:event_profileButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Cinema.hallName = hallNameField.getText();
        Cinema.movieName = movieNameField.getText();
        Cinema.showTime = showTimeField.getText();
        Cinema.noOfTickets =Integer.parseInt(numberOfTicketsField.getText());
        BillConfirmationDialog billConfirmationDialog = new BillConfirmationDialog(this, rootPaneCheckingEnabled);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void vipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vipButtonActionPerformed
        AddVipTicketFrame addVipTicketFrame = new AddVipTicketFrame();
        this.dispose();
    }//GEN-LAST:event_vipButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTicketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTicketButton;
    public javax.swing.JLabel failedLabel;
    private javax.swing.JTextField hallNameField;
    private javax.swing.JLabel hallNameLabel;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField movieNameField;
    private javax.swing.JLabel movieNameLabel;
    private javax.swing.JTextField numberOfTicketsField;
    private javax.swing.JLabel numberOfTicketsLabel;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton removeTicketButton;
    private javax.swing.JTextField showTimeField;
    private javax.swing.JLabel showTimeLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton vipButton;
    // End of variables declaration//GEN-END:variables
}
