/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.programming3;

import java.util.ArrayList;

/**
 *
 * @author omarm
 */
public class AvailableSeatsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AvailableSeatsFrame
     */
    public AvailableSeatsFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        boolean b = false;
        String hallName = Cinema.hallName;
        String movieName = Cinema.movieName;
        String movieDate = Cinema.showTime;
        String availableSeats = "";
        ArrayList<Movie> tempMovies1 = new ArrayList<>();
        tempMovies1 = Cinema.readMoviesHallFile(hallName);
        for (Movie m : tempMovies1) {
            if (movieName.equals(m.getName()) && movieDate.equals(m.getDate())) {
                if (m.getAvailableSeats() > 0) {
                    b = true;
                    int count = 1;
                    int size = 1;
                    for (int number : m.getSeats()) {
                        if (m.seats.size() == size) {
                            availableSeats = availableSeats.concat(Integer.toString(number));
                            break;
                        } else if (count == 10) {
                            availableSeats = availableSeats.concat(Integer.toString(number));
                            count++;
                        } else if (count < 10) {
                            availableSeats = availableSeats.concat(" ".concat(Integer.toString(number).concat(", ")));
                            count++;
                        } else {
                            count = 2;
                            availableSeats = availableSeats.concat("\n ".concat(Integer.toString(number)).concat(", "));

                        }
                        size++;
                    }
                } else {
                    b = false;
                    availableSeats = "No Available Seats!";
                    break;
                }

                break;
            }
        }

        //if the boolean b is true: the user can book seat, else he can't!
        //here you send the availableSeats to the text area!
        if(b) {
            availableSeatsField.append(availableSeats);
        }
        
        else {
            availableSeatsField.setText("No Available Seats!");
            seatNumberField.setEditable(false);
            submitButton.setEnabled(false);
        }
        availableSeatsField.setEditable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        availableSeatsLabel = new javax.swing.JLabel();
        seatNumberLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableSeatsField = new javax.swing.JTextArea();
        seatNumberField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        availableSeatsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        availableSeatsLabel.setForeground(new java.awt.Color(35, 179, 155));
        availableSeatsLabel.setText("Available Seats :");

        seatNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seatNumberLabel.setForeground(new java.awt.Color(35, 179, 155));
        seatNumberLabel.setText("Enter Seat Number :");

        availableSeatsField.setColumns(20);
        availableSeatsField.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        availableSeatsField.setForeground(new java.awt.Color(28, 141, 122));
        availableSeatsField.setRows(5);
        jScrollPane1.setViewportView(availableSeatsField);

        seatNumberField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        submitButton.setBackground(new java.awt.Color(35, 179, 155));
        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setFocusable(false);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(227, 6, 50));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("Back");
        homeButton.setFocusable(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(availableSeatsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(homeButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(submitButton))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatNumberLabel)
                                .addComponent(seatNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(availableSeatsLabel)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(seatNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeButton))
                        .addContainerGap(135, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Cinema.noOfVIPSeat = Integer.parseInt(seatNumberField.getText());
        BillConfirmationDialog billConfirmationDialog = new BillConfirmationDialog(this, rootPaneCheckingEnabled);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        AddVipTicketFrame addVipTicketFrame = new AddVipTicketFrame();
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvailableSeatsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvailableSeatsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvailableSeatsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvailableSeatsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvailableSeatsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea availableSeatsField;
    private javax.swing.JLabel availableSeatsLabel;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField seatNumberField;
    private javax.swing.JLabel seatNumberLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
